lock:
  description: >
    Turn on the guard
  fields:
    id:
      description: >
        The ID of Pandora device (PANDORA_ID)
      example: 1234567

unlock:
  description: >
    Turn off the guard
  fields:
    id:
      description: >
        The ID of Pandora device (PANDORA_ID)
      example: 1234567

start_engine:
  description: >
    Start engine
  fields:
    id:
      description: >
        The ID of Pandora device (PANDORA_ID)
      example: 1234567

stop_engine:
  description: >
    Stop engine
  fields:
    id:
      description: >
        The ID of Pandora device (PANDORA_ID)
      example: 1234567

turn_on_ext_channel:
  description: >
    Turn on external channel (GSM)
  fields:
    id:
      description: >
        The ID of Pandora device (PANDORA_ID)
      example: 1234567

turn_off_ext_channel:
  description: >
    Turn off external channel (GSM)
  fields:
    id:
      description: >
        The ID of Pandora device (PANDORA_ID)
      example: 1234567

turn_on_coolant_heater:
  description: >
    Turn on coolant heater
  fields:
    id:
      description: >
        The ID of Pandora device (PANDORA_ID)
      example: 1234567

turn_off_coolant_heater:
  description: >
    Turn off coolant heater
  fields:
    id:
      description: >
        The ID of Pandora device (PANDORA_ID)
      example: 1234567
